"""initial_migration

Revision ID: 834e8b4698c0
Revises: 5884540189a2
Create Date: 2025-09-17 11:08:04.664225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834e8b4698c0'
down_revision: Union[str, Sequence[str], None] = '5884540189a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('cell', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('corpo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_tags',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.drop_table('projeto_tags')
    op.drop_table('projetos')
    op.drop_table('aluno')
    op.add_column('tags', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('tags', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('nome', sa.VARCHAR(), nullable=True))
    op.drop_column('tags', 'name')
    op.create_table('aluno',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('curso', sa.VARCHAR(), nullable=True),
    sa.Column('celular', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), nullable=True),
    sa.Column('titulo', sa.VARCHAR(), nullable=True),
    sa.Column('foto', sa.VARCHAR(), nullable=True),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.Column('corpo', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto_tags',
    sa.Column('projeto_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.drop_table('project_tags')
    op.drop_table('project')
    op.drop_table('student')
    # ### end Alembic commands ###
