"""novas alterações

Revision ID: accf8e14507f
Revises: 0ce66c41b573
Create Date: 2025-09-17 12:37:54.661951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accf8e14507f'
down_revision: Union[str, Sequence[str], None] = '0ce66c41b573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
